[project]
name = "rt-processor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.14.13",
    "pytest>=8.4.1",
    "requests>=2.32.4",
    "ruff>=0.12.5",
]
